spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hack #dev
    username: postgres
    password: psql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  #Additional Spring configuration
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    expose-request-attributes: true
  devtools:
    livereload:
      enabled: false
    add-properties: false
  jmx:
    default-domain: loc
server:
  servlet:
    session:
      timeout: 1920m
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/pdf
  port: 8080